package edu.pe.unsch.entity;
// Generated 24-jul-2019 23:10:45 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Docente generated by hbm2java
 */
@Entity
@Table(name = "docente", catalog = "ratificacionbd")
public class Docente implements java.io.Serializable {

	private Integer idDocente;
	private Facultad facultad;
	private Persona persona;
	private Set<Expediente> expedientes = new HashSet<Expediente>(0);
	private Set<Expediente> expedientes_1 = new HashSet<Expediente>(0);

	public Docente() {
	}

	public Docente(Facultad facultad, Persona persona, Set<Expediente> expedientes, Set<Expediente> expedientes_1) {
		this.facultad = facultad;
		this.persona = persona;
		this.expedientes = expedientes;
		this.expedientes_1 = expedientes_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_docente", unique = true, nullable = false)
	public Integer getIdDocente() {
		return this.idDocente;
	}

	public void setIdDocente(Integer idDocente) {
		this.idDocente = idDocente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_facultad")
	public Facultad getFacultad() {
		return this.facultad;
	}

	public void setFacultad(Facultad facultad) {
		this.facultad = facultad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona")
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "docente")
	public Set<Expediente> getExpedientes() {
		return this.expedientes;
	}

	public void setExpedientes(Set<Expediente> expedientes) {
		this.expedientes = expedientes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "docente")
	public Set<Expediente> getExpedientes_1() {
		return this.expedientes_1;
	}

	public void setExpedientes_1(Set<Expediente> expedientes_1) {
		this.expedientes_1 = expedientes_1;
	}

}
