package edu.pe.unsch.entity;
// Generated 24-jul-2019 23:10:45 by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Documento generated by hbm2java
 */
@Entity
@Table(name = "documento", catalog = "ratificacionbd", uniqueConstraints = @UniqueConstraint(columnNames = "cod_documento"))
public class Documento implements java.io.Serializable {

	private Integer idDocumento;
	private Usuario usuario;
	private String codDocumento;
	private Date fechaPresentacion;
	private String contenido;

	public Documento() {
	}

	public Documento(Date fechaPresentacion) {
		this.fechaPresentacion = fechaPresentacion;
	}

	public Documento(Usuario usuario, String codDocumento, Date fechaPresentacion, String contenido) {
		this.usuario = usuario;
		this.codDocumento = codDocumento;
		this.fechaPresentacion = fechaPresentacion;
		this.contenido = contenido;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_documento", unique = true, nullable = false)
	public Integer getIdDocumento() {
		return this.idDocumento;
	}

	public void setIdDocumento(Integer idDocumento) {
		this.idDocumento = idDocumento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario")
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "cod_documento", unique = true, length = 30)
	public String getCodDocumento() {
		return this.codDocumento;
	}

	public void setCodDocumento(String codDocumento) {
		this.codDocumento = codDocumento;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_presentacion", nullable = false, length = 10)
	public Date getFechaPresentacion() {
		return this.fechaPresentacion;
	}

	public void setFechaPresentacion(Date fechaPresentacion) {
		this.fechaPresentacion = fechaPresentacion;
	}

	@Column(name = "contenido", length = 65535)
	public String getContenido() {
		return this.contenido;
	}

	public void setContenido(String contenido) {
		this.contenido = contenido;
	}

}
