package edu.pe.unsch.entity;
// Generated 24-jul-2019 23:10:45 by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Expediente generated by hbm2java
 */
@Entity
@Table(name = "expediente", catalog = "ratificacionbd")
public class Expediente implements java.io.Serializable {

	private Integer idExpediente;
	private Docente docente;
	private Date fechaPresentacion;
	private String contenidoExpediente;

	public Expediente() {
	}

	public Expediente(String contenidoExpediente) {
		this.contenidoExpediente = contenidoExpediente;
	}

	public Expediente(Docente docente, Date fechaPresentacion, String contenidoExpediente) {
		this.docente = docente;
		this.fechaPresentacion = fechaPresentacion;
		this.contenidoExpediente = contenidoExpediente;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_expediente", unique = true, nullable = false)
	public Integer getIdExpediente() {
		return this.idExpediente;
	}

	public void setIdExpediente(Integer idExpediente) {
		this.idExpediente = idExpediente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_docente")
	public Docente getDocente() {
		return this.docente;
	}

	public void setDocente(Docente docente) {
		this.docente = docente;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_presentacion", length = 10)
	public Date getFechaPresentacion() {
		return this.fechaPresentacion;
	}

	public void setFechaPresentacion(Date fechaPresentacion) {
		this.fechaPresentacion = fechaPresentacion;
	}

	@Column(name = "contenido_expediente", nullable = false, length = 65535)
	public String getContenidoExpediente() {
		return this.contenidoExpediente;
	}

	public void setContenidoExpediente(String contenidoExpediente) {
		this.contenidoExpediente = contenidoExpediente;
	}

}
